language: python

sudo: false

env:
  matrix:
    - BUILD_CMD='html'
            
python:
    - 3.6

virtualenv:
     system_site_packages: false

install:
    - pip install -r requirements.txt

script:
    - make $BUILD_CMD
